CREATE TABLE IF NOT EXISTS task_logs (
    task_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id INT NOT NULL DEFAULT 0,

    input_parameter_names TEXT[] NOT NULL DEFAULT '{}',
    output_parameter_names TEXT[] NOT NULL DEFAULT '{}',
    status BOOLEAN[] NOT NULL DEFAULT '{}',

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    input_parameter_values TEXT[] NOT NULL DEFAULT '{}',
    output_parameter_real_values TEXT[] NOT NULL DEFAULT '{}',
    output_parameter_from_code_values TEXT[] NOT NULL DEFAULT '{}'
);