CREATE TABLE IF NOT EXISTS tasks (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        cron_spec TEXT NOT NULL,
        payload TEXT,
        last_run INTEGER DEFAULT 0);