CREATE TABLE IF NOT EXISTS tasks (
        task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        time_interval TEXT NOT NULL,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_run TIMESTAMPTZ DEFAULT NULL,
        start_time TIMESTAMPTZ NOT NULL DEFAULT now(),
        end_time TIMESTAMPTZ NOT NULL DEFAULT now(),
        machine_id INTEGER NOT NULL DEFAULT 0,
        input_parameters TEXT[] NOT NULL DEFAULT '{}',
        output_parameters TEXT[] NOT NULL DEFAULT '{}',
        output_parameters_error_rate INTEGER[] NOT NULL DEFAULT '{}',
        file_path TEXT NOT NULL DEFAULT ''
        );