// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/devices": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all devices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Returns all devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.DeviceListOutputModel"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/devices/getDeviceParameters/{device_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "returns device parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "returns device parameters",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "device ID",
                        "name": "device_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/GetTaskDetail/{task_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "returns the details of a task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "returns the details of a task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.TaskDetailOutputModel"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new task",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Creates a new task",
                "parameters": [
                    {
                        "type": "file",
                        "description": "C++ or Python or Java or Javascript source file to scan",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of task",
                        "name": "taskName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID of the device",
                        "name": "deviceId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "interval time in minutes",
                        "name": "intervalTimeInMinutes",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "input parmas",
                        "name": "inputParameters",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "output parmas",
                        "name": "outputParameters",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "description": "output parmas error percentage",
                        "name": "acceptableErrorPercentage",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "start time in UTC and RFC3339 format (e.g. 2025-08-18T14:30:00Z)",
                        "name": "startTime",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "end time in UTC and RFC3339 format (e.g. 2025-08-18T14:30:00Z)",
                        "name": "endTime",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.SaveTaskResult"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/getTaskList": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all tasks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Returns all tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.TaskOutputModel"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.AcceptableErrorPercentage": {
            "type": "object",
            "properties": {
                "errorPercentage": {
                    "type": "integer"
                },
                "parameterName": {
                    "type": "string"
                }
            }
        },
        "main.DeviceListOutputModel": {
            "type": "object",
            "properties": {
                "deviceId": {
                    "type": "integer"
                },
                "deviceName": {
                    "type": "string"
                }
            }
        },
        "main.InputParameter": {
            "type": "object",
            "properties": {
                "parameterName": {
                    "type": "string"
                },
                "parameterValue": {
                    "type": "string"
                }
            }
        },
        "main.OutputParameter": {
            "type": "object",
            "properties": {
                "parameterDeviceValue": {
                    "type": "string"
                },
                "parameterName": {
                    "type": "string"
                },
                "parameterSimulationValue": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "main.SaveTaskResult": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "string"
                },
                "taskId": {
                    "type": "integer"
                }
            }
        },
        "main.TaskDetailOutputModel": {
            "type": "object",
            "properties": {
                "acceptableErrorPercentage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.AcceptableErrorPercentage"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.TaskLog"
                    }
                },
                "deviceId": {
                    "type": "integer"
                },
                "deviceName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "pluginOperatingHours": {
                    "type": "number"
                },
                "systemErrorPercentage": {
                    "type": "number"
                },
                "taskId": {
                    "type": "integer"
                },
                "taskName": {
                    "type": "string"
                }
            }
        },
        "main.TaskLog": {
            "type": "object",
            "properties": {
                "inputParameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.InputParameter"
                    }
                },
                "outputParameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.OutputParameter"
                    }
                },
                "runTime": {
                    "type": "string"
                }
            }
        },
        "main.TaskOutputModel": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deviceId": {
                    "type": "integer"
                },
                "deviceName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "pluginOperatingHours": {
                    "type": "number"
                },
                "taskId": {
                    "type": "integer"
                },
                "taskName": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your bearer token in the format **Bearer \u0026lt;token\u0026gt;**",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "DigitalTwin API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
