definitions:
  main.AcceptableErrorPercentage:
    properties:
      errorPercentage:
        type: integer
      parameterName:
        type: string
    type: object
  main.DeviceListOutputModel:
    properties:
      deviceId:
        type: integer
      deviceName:
        type: string
    type: object
  main.InputParameter:
    properties:
      parameterName:
        type: string
      parameterValue:
        type: string
    type: object
  main.OutputParameter:
    properties:
      parameterDeviceValue:
        type: string
      parameterName:
        type: string
      parameterSimulationValue:
        type: string
      status:
        type: boolean
    type: object
  main.SaveTaskResult:
    properties:
      errors:
        type: string
      taskId:
        type: integer
    type: object
  main.StopTaskResultModel:
    properties:
      success:
        type: boolean
    type: object
  main.TaskDetailOutputModel:
    properties:
      acceptableErrorPercentage:
        items:
          $ref: '#/definitions/main.AcceptableErrorPercentage'
        type: array
      createdAt:
        type: string
      data:
        items:
          $ref: '#/definitions/main.TaskLog'
        type: array
      deviceId:
        type: integer
      deviceName:
        type: string
      isActive:
        type: boolean
      pluginOperatingHours:
        type: number
      systemErrorPercentage:
        type: number
      taskId:
        type: integer
      taskName:
        type: string
    type: object
  main.TaskLog:
    properties:
      inputParameters:
        items:
          $ref: '#/definitions/main.InputParameter'
        type: array
      outputParameters:
        items:
          $ref: '#/definitions/main.OutputParameter'
        type: array
      runTime:
        type: string
    type: object
  main.TaskOutputModel:
    properties:
      createdAt:
        type: string
      deviceId:
        type: integer
      deviceName:
        type: string
      isActive:
        type: boolean
      pluginOperatingHours:
        type: number
      taskId:
        type: integer
      taskName:
        type: string
    type: object
info:
  contact: {}
  title: DigitalTwin API
  version: "1.0"
paths:
  /api/v1/devices/{page}:
    get:
      consumes:
      - application/json
      description: Returns devices with pagination
      parameters:
      - description: number of page
        in: path
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.DeviceListOutputModel'
            type: array
      security:
      - BearerAuth: []
      summary: Returns devices with pagination
      tags:
      - devices
  /api/v1/devices/getDeviceParameters/{device_id}:
    get:
      consumes:
      - application/json
      description: returns device parameters
      parameters:
      - description: device ID
        in: path
        name: device_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      security:
      - BearerAuth: []
      summary: returns device parameters
      tags:
      - devices
  /api/v1/tasks/GetTaskDetail/{task_id}:
    get:
      consumes:
      - application/json
      description: returns the details of a task
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.TaskDetailOutputModel'
      security:
      - BearerAuth: []
      summary: returns the details of a task
      tags:
      - tasks
  /api/v1/tasks/create:
    post:
      consumes:
      - multipart/form-data
      description: Creates a new task
      parameters:
      - description: C++ or Python or Java or Javascript source file to scan
        in: formData
        name: file
        required: true
        type: file
      - description: Name of task
        in: formData
        name: taskName
        required: true
        type: string
      - description: ID of the device
        in: formData
        name: deviceId
        required: true
        type: integer
      - description: interval time in minutes
        in: formData
        name: intervalTimeInMinutes
        required: true
        type: integer
      - collectionFormat: multi
        description: input parmas
        in: formData
        items:
          type: string
        name: inputParameters
        required: true
        type: array
      - collectionFormat: multi
        description: output parmas
        in: formData
        items:
          type: string
        name: outputParameters
        required: true
        type: array
      - collectionFormat: multi
        description: output parmas error percentage
        in: formData
        items:
          type: integer
        name: acceptableErrorPercentage
        required: true
        type: array
      - description: start time in UTC and RFC3339 format (e.g. 2025-08-18T14:30:00Z)
        format: date-time
        in: formData
        name: startTime
        required: true
        type: string
      - description: end time in UTC and RFC3339 format (e.g. 2025-08-18T14:30:00Z)
        format: date-time
        in: formData
        name: endTime
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.SaveTaskResult'
      security:
      - BearerAuth: []
      summary: Creates a new task
      tags:
      - tasks
  /api/v1/tasks/delete/{task_id}:
    delete:
      consumes:
      - application/json
      description: deletes an existing task
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: deletes an existing task
      tags:
      - tasks
  /api/v1/tasks/getTaskList/{page}:
    get:
      consumes:
      - application/json
      description: returns tasks with pagination
      parameters:
      - description: number of page
        in: path
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.TaskOutputModel'
            type: array
      security:
      - BearerAuth: []
      summary: returns tasks with pagination
      tags:
      - tasks
  /api/v1/tasks/stopTask/{task_id}:
    post:
      consumes:
      - application/json
      description: stops a task from running
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.StopTaskResultModel'
      security:
      - BearerAuth: []
      summary: stops a task from running
      tags:
      - tasks
securityDefinitions:
  BearerAuth:
    description: Enter your bearer token in the format **Bearer &lt;token&gt;**
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
